services:
  compiler:
    image: batonogov/pyinstaller-windows:latest
    entrypoint: /bin/bash
    working_dir: /src/
    volumes:
      - ./:/src/
    command: >
      -c "
      pip install -r requirements.txt &&
      bash build.sh
      "